### ISSUE TITLE
Make the conversion functions return a result instead of exception

### ISSUE THREAD

**Issue by Khady** [andersfugmann/ppx_protocol_conv#13]
I started to change the code of merlin-lsp from ppx_deriving_yojson to ppx_protocol_conv_json. It is mostly mechanical work that does not create problems. And this new ppx adds some nice features. But there is one annoying point. The `of_yojson` functions of ppx_deriving_yojson are returning a result rather. ppx_protocol_conv creates functions that raise exceptions. In general, I think that it is preferable to use the result type.

Would it be possible to follow the same behavior than ppx_deriving_yojson? With eventually an optional way to generate the `of_json_exn` function if necessary?

If it makes sense for you, I could try to contribute to the change.

https://github.com/ocaml/merlin/pull/948
https://github.com/ocaml-ppx/ppx_deriving_yojson#syntax

**Comment by andersfugmann** [comment]
It really a matter of style if you prefer the one over the other, but I do agree that it might be better to explicitly make the users aware that deserialisation may fail. 

However, consider this case: 
```
type t = { a: int; b: lazy int }
```
Currently deserialisation will create a `forced` lazy. But I'm planning to allow user to enable 'real' laziness here, meaning that `b`would only be deserialised when `b`is forced (i.e. `b` would actually hold on the its serialized representation until that point). this also means that forcing `b` might fail. And since it not possible to change the signature of `t`, `b` still needs to have the type `lazy int`. So 'b' cannot have type `(int, 'a) Result.t lazy`.

But as you say, the code could just emit two versions (`t_to_driver` and `t_to_driver_exn`). 
Its not a hard change to the code, as the non exception version would just catch any raised exception and return `(t, 'a) Result.t`

I do welcome PR's, but I'm currently in the middle of a major rewrite (#14), so any PR made before #14 is merged is likely to have alot of merge conflicts.

**Comment by andersfugmann** [comment]
Implemented on master. 
`of_driver` returns a `(t, exn) result`,
and an `of_driver_exn` returns t, and may raise exceptions.

**Comment by Khady** [comment]
thanks!

**Comment by paurkedal** [comment]
I think this is a nice change, but don't think it's optimal to use the exception type as the `Error` argument.  The reason is that since the exception type is open, pattern matching on `Ok _` and `Error (Protocol_error ..)` will be non-exhaustive.  My suggestion would be something along the lines of
```ocaml
type protocol_error = private {msg : string; value: t option}
[@@deriving show] (* or better: a customized equivalent of the API *)

val protocol_error : ?value: t -> string -> protocol_error

exception Protocol_error of protocol_error
```
The reason to make the error type private and provide a custom constructor is to allow new fields is the future.  E.g. a ``path: [`Label of string | `Index of int] list`` to track where in the message an offending value occurred would be very handy for debugging protocol issues, but it will take some work to implement, so it would be premature to add it now.

**Comment by andersfugmann** [comment]
Merged to master
