### ISSUE TITLE
yaml 3.0.0 changes output format

### ISSUE THREAD

**Issue by avsm** [andersfugmann/ppx_protocol_conv#35]
Yaml 3.0.0 now detects special strings (like `true` or `1.0`) and quotes them so that they can be reconstructed as strings and not interpreted as floats or bools.

This breaks the test cases in ppx_protocol_conv_yaml, so I've added an upper bound in https://github.com/ocaml/opam-repository/pull/19204 for this.  The yaml 3.0.0 release is in https://github.com/ocaml/opam-repository/pull/19202

**Comment by andersfugmann** [comment]
Thanks for the heads up. 
I have updated the tests to be compatible with the output of `yaml >= 3.0.0`, and will release a new version of the library shortly.

From an Ocaml pow, it seems good to quote strings which would otherwise be interpreted as a non string type.  However, its not very idiomatic for yaml to have quoted values. Maybe the ppx_protocol_conv should work over type `Yaml.yaml` and not `Yaml.t` and do serialization manually.

**Comment by avsm** [comment]
If you need finer control, then using Yaml.yaml is definitely the right way to go. You should be able to control every aspect of the serialisation using that.

Preserving the property that serialisation and deserialisation result in the same values would be very useful -- Yaml is particularly confusing when it comes to magical interpretations :-)

**Comment by andersfugmann** [comment]
Indeed - the yaml format is quite confusing. Even `js-yaml` deserialization tries to guess the type of the fields. 

I have created a PR to depend on `yaml >= 3.0.0` with tests now that yaml 3.0.0 is out:  
https://github.com/ocaml/opam-repository/pull/19214
